### ISSUE TITLE
List return

### ISSUE THREAD

**Issue by beatorizu** [Try2Code/cdo-bindings#11] opened 2017-01-19 18:31 UTC
It could be interesting if commands like showname, showtimestamp returne a list of results no a list of a single string. 

When I run 
```python
In[3]: cdo.showdate(input='/some/file/')
```
```python
# return like this
Out[3]: ['2017-01-19  2017-01-20  2017-01-21  2017-01-22  2017-01-23  2017-01-24  2017-01-25  2017-01-26']
```

Then I run
```python
In[4]: cdo.showdate(input='/some/file/')[0].split('  ')
Out[4]: ['2017-01-19',
         '2017-01-20',
         '2017-01-21',
         '2017-01-22',
         '2017-01-23',
         '2017-01-24',
         '2017-01-25',
         '2017-01-26']
```

I believe it is better if this is a built-in function. Is this could be improved?

**Comment by Try2Code** [comment] 2017-02-15 15:05
Hi + sorry for the delay
the problem is, that this solutions looks good for a single line (showname,showdate,showtime,showyear,showcode) but becomes tricky for things like showlevel, where multiple vertical axes are shown (one line per variable). it looks like this

```
% cdo showlevel ../icon/oce.nc                                                                                                                                                                                       [Wed 2017-02-15|16:01:52]
 250 750 1250 1750 2250 2750 3250 3750 4250 4750
 0
 0
 0
 0
 0
 250 750 1250 1750 2250 2750 3250 3750 4250 4750
 250 750 1250 1750 2250 2750 3250 3750 4250 4750
 250 750 1250 1750 2250 2750 3250 3750 4250 4750
 250 750 1250 1750 2250 2750 3250 3750 4250 4750
 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000
 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000
 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000
 250 750 1250 1750 2250 2750 3250 3750 4250 4750
 25 100 250 500 875 1400 2100 3000 4000 5000
 25 100 250 500 875 1400 2100 3000 4000 5000
```

To be consistent with your suggestion the return value should be a nested array, which reduces the beauty of it.
Do you have any suggestion for this?

cheers
ralf

**Comment by beatorizu** [comment] 2017-02-18 21:04
It could be added a argument to return a list or return a string. This let us choose the format of output.

**Comment by Try2Code** [comment] 2017-02-20 12:38
I finished a first guess. Could you have a look and run some tests on it? Pls check if it's useful for you

cheers
ralf

**Comment by Try2Code** [comment] 2017-02-22 09:01
Added some code to return the list directly if the operator outputs only a single line like showname, showdate or showtimestamp.

**Comment by Try2Code** [comment] 2017-02-24 11:35
I close this one - IMO the feature is there. but pls, feel free to open an new ticket, if anything is missing.

cheers + thanks !
-ralf

**Closed by Try2Code** 2017-02-24 11:35 UTC

**Comment by beatorizu** [comment] 2017-04-19 01:38
Hi, again + sorry for the delay

I've tested the autoSplit argument and it works fine. Thank you for the improvement :+1: 

```python
In [3]: cdo.showdate(input='/path/to/some_file.nc', autoSplit='  ')
Out[3]: 
['2017-04-18',
 '2017-04-19',
 '2017-04-20',
 '2017-04-21',
 '2017-04-22',
 '2017-04-23',
 '2017-04-24',
 '2017-04-25']
```

**Comment by Try2Code** [comment] 2017-04-19 08:06
thx for testing and your input!
